# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Argument_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 850)
        MainWindow.setMinimumSize(QtCore.QSize(485, 850))
        MainWindow.setMaximumSize(QtCore.QSize(648, 850))
        MainWindow.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(51,53,66); border-style: outset;border-radius:6px; ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(69,71,85)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(70, -1, 70, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(25, 0))
        self.label_2.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(25, 0))
        self.label_3.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_2.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_3.addWidget(self.textEdit_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setMinimumSize(QtCore.QSize(40, 0))
        self.label_10.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.textEdit_9 = QtWidgets.QTextEdit(self.frame_10)
        self.textEdit_9.setMinimumSize(QtCore.QSize(100, 0))
        self.textEdit_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_9.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_2.addWidget(self.textEdit_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 57))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(-1, -1, 139, -1)
        self.horizontalLayout_6.setSpacing(27)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_3.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_6.addWidget(self.textEdit_3)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 57))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(-1, -1, 137, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_4.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_7.addWidget(self.textEdit_4)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(-1, -1, 207, -1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_5.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_8.addWidget(self.textEdit_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.textEdit_6 = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_6.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_9.addWidget(self.textEdit_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(-1, -1, 236, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.textEdit_8 = QtWidgets.QTextEdit(self.frame_6)
        self.textEdit_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_8.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_10.addWidget(self.textEdit_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_11.setSpacing(13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.textEdit_7 = QtWidgets.QTextEdit(self.frame_6)
        self.textEdit_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_7.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_7.setObjectName("textEdit_7")
        self.horizontalLayout_11.addWidget(self.textEdit_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_14.setContentsMargins(-1, -1, 101, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_2.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_2.setStyleSheet("background-color:white;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_2)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setContentsMargins(-1, -1, 189, -1)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.comboBox = QtWidgets.QComboBox(self.frame_8)
        self.comboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox.setStyleSheet("background-color:white;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_13.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.textEdit_10 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_10.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_13.addWidget(self.textEdit_10)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(110, -1, 110, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 2)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(9, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "参数调整"))
        self.label.setText(_translate("MainWindow", "误差微调："))
        self.label_2.setText(_translate("MainWindow", "X:"))
        self.label_3.setText(_translate("MainWindow", "Y:"))
        self.label_13.setText(_translate("MainWindow", "默认深度："))
        self.label_10.setText(_translate("MainWindow", "Z:"))
        self.label_4.setText(_translate("MainWindow", "检测矩形阈值："))
        self.label_5.setText(_translate("MainWindow", "夹爪到末端距离："))
        self.label_6.setText(_translate("MainWindow", "USB_Idv:"))
        self.label_7.setText(_translate("MainWindow", "USB_Idp:"))
        self.label_9.setText(_translate("MainWindow", "相机ID:"))
        self.label_8.setText(_translate("MainWindow", "COM:"))
        self.label_14.setText(_translate("MainWindow", "是否开启夹爪线程："))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "True"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "False"))
        self.label_11.setText(_translate("MainWindow", "Agent调用："))
        self.comboBox.setItemText(0, _translate("MainWindow", "Local"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Qwen"))
        self.label_12.setText(_translate("MainWindow", "Key："))
        self.pushButton.setText(_translate("MainWindow", "调整"))
