# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        MainWindow.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(51,53,66); border-style: outset;border-radius:6px; ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(69,71,85)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setMinimumSize(QtCore.QSize(660, 280))
        self.scrollArea.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(69,71,85); border-style: outset;border-radius:6px; ")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 804, 707))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setStyleSheet("font: 18pt \"Arial\";\n"
"color:white;\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        self.frame_5.setStyleSheet("background-color: none;\n"
"border: none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 9)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(320, 240))
        self.label.setMaximumSize(QtCore.QSize(320, 240))
        self.label.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(221,221,221);width:640px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(320, 240))
        self.label_3.setMaximumSize(QtCore.QSize(320, 240))
        self.label_3.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(221,221,221)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit_2.setStyleSheet("background: white;\n"
"font: 11pt \"Arial\";\n"
"")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_6.addWidget(self.textEdit_2)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_24.setContentsMargins(2, 0, 5, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(7, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setStyleSheet("border: none;color: white;\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setMinimumSize(QtCore.QSize(50, 40))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_13.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.horizontalLayout_7.setStretch(0, 3)
        self.horizontalLayout_7.setStretch(1, 7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setStyleSheet("border:none;\n"
"color: white;\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_14.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.horizontalLayout_10.setStretch(0, 3)
        self.horizontalLayout_10.setStretch(1, 7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setStyleSheet("border: none;\n"
"color: white;\n"
"")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setMinimumSize(QtCore.QSize(50, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_15.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.horizontalLayout_11.setStretch(0, 3)
        self.horizontalLayout_11.setStretch(1, 7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_24.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(7, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setStyleSheet("border: none;color:white;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_16.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.horizontalLayout_12.setStretch(0, 3)
        self.horizontalLayout_12.setStretch(1, 7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setStyleSheet("border:none;color:white;\n"
"")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_17.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";\n"
"")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setStyleSheet("border:none;color: white;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_18.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.horizontalLayout_14.setStretch(0, 3)
        self.horizontalLayout_14.setStretch(1, 7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_24.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(7, -1, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setStyleSheet("border:none;color: white;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.frame_7)
        self.label_20.setMinimumSize(QtCore.QSize(50, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_20.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.horizontalLayout_15.setStretch(0, 3)
        self.horizontalLayout_15.setStretch(1, 7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtWidgets.QLabel(self.frame_7)
        self.label_21.setStyleSheet("border:none;color: white;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_22.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.horizontalLayout_18.setStretch(0, 3)
        self.horizontalLayout_18.setStretch(1, 7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setStyleSheet("border:none;color: white;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        self.label_24.setMinimumSize(QtCore.QSize(50, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_24.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";\n"
"")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.horizontalLayout_19.setStretch(0, 3)
        self.horizontalLayout_19.setStretch(1, 7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_24.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(7, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtWidgets.QLabel(self.frame_7)
        self.label_25.setStyleSheet("border:none;color: white;")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.frame_7)
        self.label_26.setMinimumSize(QtCore.QSize(50, 0))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_26.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";\n"
"")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_20.addWidget(self.label_26)
        self.horizontalLayout_20.setStretch(0, 3)
        self.horizontalLayout_20.setStretch(1, 7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setStyleSheet("border:none;color: white;")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setMinimumSize(QtCore.QSize(50, 0))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_28.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_21.addWidget(self.label_28)
        self.horizontalLayout_21.setStretch(0, 3)
        self.horizontalLayout_21.setStretch(1, 7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_31 = QtWidgets.QLabel(self.frame_7)
        self.label_31.setStyleSheet("border:none;color: white;")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.frame_7)
        self.label_32.setMinimumSize(QtCore.QSize(50, 0))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_32.setStyleSheet("background: white;\n"
"font: 7pt \"Arial\";")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_23.addWidget(self.label_32)
        self.horizontalLayout_23.setStretch(0, 3)
        self.horizontalLayout_23.setStretch(1, 7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24.addLayout(self.verticalLayout_9)
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 4)
        self.verticalLayout_4.setStretch(4, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(250, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_2.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(51,53,66); border-style: outset;border-radius:6px; ")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(69,71,85); border-style: outset;border-radius:6px; ")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_9.addWidget(self.pushButton_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_12.setEnabled(False)
        self.pushButton_12.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton_12.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_7.addWidget(self.pushButton_12)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(69,71,85); border-style: outset;border-radius:6px; ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 15px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 40))
        self.comboBox.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setEnabled(False)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_2.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_3.setStyleSheet("background: white;\n"
"font: 9pt \"Arial\";\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_16.addWidget(self.textEdit_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton_6.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_16.addWidget(self.pushButton_6)
        self.horizontalLayout_16.setStretch(0, 4)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton_7.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_17.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setMinimumSize(QtCore.QSize(32, 40))
        self.pushButton_9.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_17.addWidget(self.pushButton_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(69,71,85); border-style: outset;border-radius:6px; ")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setStyleSheet("font: 87 14pt \"Arial\";\n"
"color: white;\n"
"border: none;\n"
"margin-bottom: 5px;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(32, 0))
        self.pushButton_2.setAccessibleDescription("")
        self.pushButton_2.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("border-width: 1px;border-style: solid;background-color: rgb(69,71,85); border-style: outset;border-radius:6px; ")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_13.setEnabled(False)
        self.pushButton_13.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_25.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_14.setEnabled(False)
        self.pushButton_14.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_25.addWidget(self.pushButton_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_15.setEnabled(False)
        self.pushButton_15.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    height: 40px;\n"
"    background-color: rgb(104,225,235); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    font: bold 15px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:rgb(69,71,85); /* 字体颜色 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(102,255,104);\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_10.addWidget(self.pushButton_15)
        self.verticalLayout.addWidget(self.frame_8)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 4)
        self.horizontalLayout_5.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 28))
        self.menubar.setStyleSheet("background: white;")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setStyleSheet("background-color: rgb(69,71,85);\n"
"color: rgb(255, 255, 255);")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionrecord = QtWidgets.QAction(MainWindow)
        self.actionrecord.setObjectName("actionrecord")
        self.actioncalibration = QtWidgets.QAction(MainWindow)
        self.actioncalibration.setObjectName("actioncalibration")
        self.actionArgument = QtWidgets.QAction(MainWindow)
        self.actionArgument.setObjectName("actionArgument")
        self.menu.addSeparator()
        self.menu.addAction(self.actionrecord)
        self.menu.addSeparator()
        self.menu.addAction(self.actioncalibration)
        self.menu.addSeparator()
        self.menu.addAction(self.actionArgument)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "机械臂上位机 V2.0"))
        self.groupBox.setTitle(_translate("MainWindow", "状态"))
        self.label_6.setText(_translate("MainWindow", "1轴："))
        self.label_8.setText(_translate("MainWindow", "2轴："))
        self.label_11.setText(_translate("MainWindow", "3轴："))
        self.label_9.setText(_translate("MainWindow", "4轴："))
        self.label_12.setText(_translate("MainWindow", "5轴："))
        self.label_10.setText(_translate("MainWindow", "6轴："))
        self.label_19.setText(_translate("MainWindow", "x:"))
        self.label_21.setText(_translate("MainWindow", "y:"))
        self.label_23.setText(_translate("MainWindow", "z:"))
        self.label_25.setText(_translate("MainWindow", "α："))
        self.label_27.setText(_translate("MainWindow", "β:"))
        self.label_31.setText(_translate("MainWindow", "γ:"))
        self.pushButton_5.setText(_translate("MainWindow", "连接"))
        self.pushButton_10.setText(_translate("MainWindow", "校准机械臂"))
        self.pushButton_12.setText(_translate("MainWindow", "归位"))
        self.label_4.setText(_translate("MainWindow", "机械臂控制"))
        self.pushButton.setText(_translate("MainWindow", "发送"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1轴"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2轴"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3轴"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4轴"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5轴"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6轴"))
        self.pushButton_6.setText(_translate("MainWindow", "发送"))
        self.pushButton_7.setText(_translate("MainWindow", "使能"))
        self.pushButton_9.setText(_translate("MainWindow", "失能"))
        self.label_2.setText(_translate("MainWindow", "视觉抓取"))
        self.pushButton_3.setText(_translate("MainWindow", "开启"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.pushButton_11.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_2.setText(_translate("MainWindow", "深度计算"))
        self.pushButton_8.setText(_translate("MainWindow", "识别抓取"))
        self.pushButton_13.setText(_translate("MainWindow", "Agent打开"))
        self.pushButton_14.setText(_translate("MainWindow", "Agent关闭"))
        self.pushButton_15.setText(_translate("MainWindow", "对话"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionrecord.setText(_translate("MainWindow", "录制"))
        self.actioncalibration.setText(_translate("MainWindow", "标定"))
        self.actionArgument.setText(_translate("MainWindow", "更多参数"))
